const TEXT = {
  EN: {
    LANG: 'Language',
    LANG_EN: 'ENG',
    LANG_RU: 'RUS',
    SIGNUP: 'Sign Up',
    SIGNUP_PROMPT: "Don't have an account? Sign Up",
    SIGNIN: 'Sign In',
    SIGNIN_PROMPT: 'Already have an account? Sign in',
    SIGNOUT: 'Sign Out',
    WELCOME_PAGE: 'Welcome',
    GRAPHIQL_PAGE: 'GraphiQL',
    HI: 'Hi!',
    ABOUT_COURSE:
      'This project was created as part of the RS School React course, which includes: components, routing, context, redux, nextjs, graphql.',
    ABOUT_PROJECT:
      'GraphiQL is a playground/IDE for graphQL requests. In this project we implemented authorization, localization, work with documentation and graphQL editor.',
    ABOUT_ANASTASIA:
      'Anastasia Mataeva set up the mui theme, implemented the graphql editor, code prettifying, response section and the welcome page with information about the project.',
    ABOUT_ANDREY:
      'Andrei Shamayeu implemented authentication and authorization/registration pages, routes, as well as requests to the API and the request menu on the graphiql page.',
    ABOUT_IVAN:
      'Ivan Gavrilin, as our team leader, set up the project and organized teamwork. In addition, he implemented localization, documentation on graphiql page and created the header and footer.',
    ANASTASIA: 'Anastasia Mataeva',
    ANDREY: 'Andrei Shamayeu',
    IVAN: 'Ivan Gavrilin',
    FOOTER_PROJECT_TEXT: 'This project was made as part of',
    THE_TEAM: 'The Team',
    PAGE_NOT_FOUND: 'Page Not Found',
    PAGE_NOT_FOUND_SUBTITLE: 'We could not find what you were looking for',
    PAGE_NOT_FOUND_INSTRUCTION:
      'Please contact the owner of the site that linked you to the original URL and let them know their link is broken.',
    PAGE_NOT_FOUND_BTN: 'Home',
    PASSWORD: 'Password',
    PASSWORD_PROMPT: 'Please enter your password',
    EMAIL_ADDRESS: 'Email Address',
    EMAIL_PROMPT: 'Please enter your email',
    FIRST_NAME: 'First Name',
    FIRST_NAME_PROMPT: 'Please enter your first name',
    LAST_NAME: 'Last Name',
    LAST_NAME_PROMPT: 'Please enter your last name',
    AGREE_TO_SUBSCRIBE:
      'I want to receive inspiration, marketing promotions and updates via email',
    YUP_EMAIL_INVALID: 'Please enter a valid email',
    YUP_EMAIL_REQUIRED: 'Email is a required field',
    YUP_PASSWORD_REQUIRED: 'Password is a required field',
    YUP_FIRST_LETTER: 'First uppercased letter',
    YUP_PASS_LENGTH: 'Minimum 8 symbols',
    YUP_PASS_STRENGTH:
      'Password strength: 1 number, 1 uppercased letter, 1 lowercased letter, 1 special character',
    YUP_TANDC: 'Rules not accepted',
    INPUT_API: 'Input API',
    NOT_SELECTED_API: 'API not selected',
    ROOT_TYPES: 'Root Types',
    SCHEMA_TYPES: 'All Schema Types',
    ENUM_VALUES: 'Enum Values',
    FIELDS: 'Fields',
    TYPE: 'Type',
    CLOSE_DOCS: 'Close docs',
    OPEN_DOCS: 'Open docs',
    NO_SCHEMA: 'No schema',
    FOLLOWING_ERROR: 'Following error occured: ',
    CANT_FIND_FIELD: "Sorry, I can't find the field ",
    HEADERS: 'Headers',
  },
  RU: {
    LANG: 'Язык',
    LANG_EN: 'АНГ',
    LANG_RU: 'РУС',
    SIGNUP: 'Регистрация',
    SIGNUP_PROMPT: 'Нет аккаунта? Зарегистрируйтесь здесь',
    SIGNIN: 'Войти',
    SIGNIN_PROMPT: 'Уже есть аккаунт? Войти',
    SIGNOUT: 'Выйти',
    WELCOME_PAGE: 'Добро пожаловать',
    GRAPHIQL_PAGE: 'Редактор GraphiQL',
    HI: 'Привет!',
    ABOUT_COURSE:
      'Этот проект был создан в рамках курса RS School React, который включает в себя: components, routing, context, redux, nextjs, graphql.',
    ABOUT_PROJECT:
      'GraphiQL - это песочница/IDE для graphQL запросов. В данном проекте мы реализовали авторизацию, локализацию, работу с документацией и редактор.',
    ABOUT_ANASTASIA:
      'Анастасия Матаева настроила mui тему, реализовала graphql редактор, форматирование кода, отображение ответа и стартовую страницу с информацией о проекте.',
    ABOUT_ANDREY:
      'Андрей Шамаев реализовал аутентификацию и соответствующие страницы авторизации/регистрации, переход по страницам, а также запросы к API и меню запросов на странице graphiql.',
    ABOUT_IVAN:
      'Иван Гаврилин, будучи лидером нашей команды, настроил проект и организовал работу. Кроме того, реализовал локализацию, документацию на странице graphiql, и создал хедер и футер.',
    ANASTASIA: 'Анастасия Матаева',
    ANDREY: 'Андрей Шамаев',
    IVAN: 'Иван Гаврилин',
    FOOTER_PROJECT_TEXT: 'Проект выполнен в рамках курса',
    THE_TEAM: 'Команда',
    PAGE_NOT_FOUND: 'Страница Не Найдена',
    PAGE_NOT_FOUND_SUBTITLE: 'Мы не смогли найти запрошенную Вами страницу',
    PAGE_NOT_FOUND_INSTRUCTION:
      'Пожалуйста сообщите администратору сайта, с которого перешли, что у них неверная ссылка. И кофе мне, Лидочка!',
    PAGE_NOT_FOUND_BTN: 'На главную',
    PASSWORD: 'Пароль',
    PASSWORD_PROMPT: 'Введите Ваш пароль',
    EMAIL_ADDRESS: 'Адрес электронной почты',
    EMAIL_PROMPT: 'Введите адрес электронной почты',
    FIRST_NAME: 'Имя',
    FIRST_NAME_PROMPT: 'Введите Ваше имя',
    LAST_NAME: 'Фамилия',
    LAST_NAME_PROMPT: 'Введите Вашу фамилию',
    AGREE_TO_SUBSCRIBE:
      'Я даю согласие на получение предложений и информации об акциях по электронной почте',
    YUP_EMAIL_INVALID: 'Неверный формат электронной почты',
    YUP_EMAIL_REQUIRED: 'Поле Электронная почта - обязательное',
    YUP_PASSWORD_REQUIRED: 'Поле Пароль - обязательное',
    YUP_FIRST_LETTER: 'Первая буква - заглавная',
    YUP_PASS_LENGTH: 'Не менее 8 символов',
    YUP_PASS_STRENGTH:
      'Пароль должен содержать: 1 цифру, 1 прописную и 1 заглавную букву, 1 специальный символ',
    YUP_TANDC: 'Забыли поставить галочку',
    INPUT_API: 'Введите API',
    NOT_SELECTED_API: 'Не выбран API',
    ROOT_TYPES: 'Корневые типы',
    SCHEMA_TYPES: 'Все типы',
    ENUM_VALUES: 'Значения Enum',
    FIELDS: 'Поля',
    TYPE: 'Тип',
    CLOSE_DOCS: 'Закрыть схему',
    OPEN_DOCS: 'Открыть схему',
    NO_SCHEMA: 'Нет схемы',
    FOLLOWING_ERROR: 'Возникла следующая ошибка: ',
    CANT_FIND_FIELD: 'Не удалось найти поле ',
    HEADERS: 'Заголовки',
  },
};

export default TEXT;
