const TEXT = {
  EN: {
    LANG: 'Language',
    LANG_EN: 'ENG',
    LANG_RU: 'RUS',
    SIGNUP: 'Sign Up',
    SIGNUP_PROMPT: "Don't have an account? Sign Up",
    SIGNIN: 'Sign In',
    SIGNIN_PROMPT: 'Already have an account? Sign in',
    SIGNOUT: 'Sign Out',
    WELCOME_PAGE: 'Welcome',
    GRAPHIQL_PAGE: 'GraphiQL',
    HI: 'Hi!',
    ANASTASIA: 'Anastasia Mataeva',
    ANDREY: 'Andrei Shamayeu',
    IVAN: 'Ivan Gavrilin',
    FOOTER_PROJECT_TEXT: 'This project was made as part of',
    THE_TEAM: 'The Team',
    PAGE_NOT_FOUND: 'Page Not Found',
    PAGE_NOT_FOUND_SUBTITLE: 'We could not find what you were looking for',
    PAGE_NOT_FOUND_INSTRUCTION:
      'Please contact the owner of the site that linked you to the original URL and let them know their link is broken.',
    PAGE_NOT_FOUND_BTN: 'Home',
    PASSWORD: 'Password',
    PASSWORD_PROMPT: 'Please enter your password',
    EMAIL_ADDRESS: 'Email Address',
    EMAIL_PROMPT: 'Please enter your email',
    FIRST_NAME: 'First Name',
    FIRST_NAME_PROMPT: 'Please enter your first name',
    LAST_NAME: 'Last Name',
    LAST_NAME_PROMPT: 'Please enter your last name',
    AGREE_TO_SUBSCRIBE:
      'I want to receive inspiration, marketing promotions and updates via email',
    YUP_EMAIL_INVALID: 'Please enter a valid email',
    YUP_EMAIL_REQUIRED: 'Email is a required field',
    YUP_PASSWORD_REQUIRED: 'Password is a required field',
    YUP_FIRST_LETTER: 'First uppercased letter',
    YUP_PASS_LENGTH: 'Minimum 8 symbols',
    YUP_PASS_STRENGTH:
      'Password strength: 1 number, 1 uppercased letter, 1 lowercased letter, 1 special character',
    YUP_TANDC: 'Rules not accepted',
  },
  RU: {
    LANG: 'Язык',
    LANG_EN: 'АНГ',
    LANG_RU: 'РУС',
    SIGNUP: 'Регистрация',
    SIGNUP_PROMPT: 'Нет аккаунта? Зарегистрируйтесь здесь',
    SIGNIN: 'Войти',
    SIGNIN_PROMPT: 'Уже есть аккаунт? Войти',
    SIGNOUT: 'Выйти',
    WELCOME_PAGE: 'Добро пожаловать',
    GRAPHIQL_PAGE: 'Редактор GraphiQL',
    HI: 'Привет!',
    ANASTASIA: 'Анастасия Матаева',
    ANDREY: 'Андрей Шамаев',
    IVAN: 'Иван Гаврилин',
    FOOTER_PROJECT_TEXT: 'Проект выполнен в рамках курса',
    THE_TEAM: 'Команда',
    PAGE_NOT_FOUND: 'Страница Не Найдена',
    PAGE_NOT_FOUND_SUBTITLE: 'Мы не смогли найти запрошенную Вами страницу',
    PAGE_NOT_FOUND_INSTRUCTION:
      'Пожалуйста сообщите администратору сайта, с которого перешли, что у них неверная ссылка. И кофе мне, Лидочка!',
    PAGE_NOT_FOUND_BTN: 'На главную',
    PASSWORD: 'Пароль',
    PASSWORD_PROMPT: 'Введите Ваш пароль',
    EMAIL_ADDRESS: 'Адрес электронной почты',
    EMAIL_PROMPT: 'Введите адрес электронной почты',
    FIRST_NAME: 'Имя',
    FIRST_NAME_PROMPT: 'Введите Ваше имя',
    LAST_NAME: 'Фамилия',
    LAST_NAME_PROMPT: 'Введите Вашу фамилию',
    AGREE_TO_SUBSCRIBE:
      'Я даю согласие на получение предложений и информации об акциях по электронной почте',
    YUP_EMAIL_INVALID: 'Неверный формат электронной почты',
    YUP_EMAIL_REQUIRED: 'Поле Электронная почта - обязательное',
    YUP_PASSWORD_REQUIRED: 'Поле Пароль - обязательное',
    YUP_FIRST_LETTER: 'Первая буква - заглавная',
    YUP_PASS_LENGTH: 'Не менее 8 символов',
    YUP_PASS_STRENGTH:
      'Пароль должен содержать: 1 цифру, 1 прописную и 1 заглавную букву, 1 специальный символ',
    YUP_TANDC: 'Забыли поставить галочку',
  },
};

export default TEXT;
